language: python
cache:
  pip: true
jobs:
  include:
    - name: "Linux Python 3.6"
      python: '3.6'
    - name: "Linux Python 3.7"
      python: '3.7'
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
      before_install:
        - cd /usr/local/bin
        - mv python python.old
        - ln -s python3 python
        - cd -
    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.4
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install -r requirements-nogpu.txt
  - python -m pip install --upgrade pytest
script: python -m pytest tests/unit_tests.py
deploy:
  provider: pypi
  user: "__token__"
  password: $pypitoken
  edge: true
  on:
    branch: master
    tags: true
    python: '3.7'
